apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-green
  # replicaset labels
  labels:
    purpose: blue-green
    project: ellamma-ecommerce
    color: green
spec:
  replicas: 4 #create 3 pods of replica
  selector:
    # these labels are used to select the pods
    matchLabels:
      purpose: blue-green
      project: ellamma-ecommerce
      color: green
# pod definition      
  template:
    metadata:
      labels:
        purpose: blue-green
        project: ellamma-ecommerce
        color: green
    spec:
      containers:
      - name: nginx
        image: nginx:mainline-alpine3.23-perl